version: '3.4'

networks:
  tmsnetwork:
    driver: bridge

services:
  gateway:
    image: tms-gatewayapi
    container_name: tms.gatewayapi
    build:
      context: .
      dockerfile: Gateway.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Container
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    links:
      - auth:auth
      - trip:trip
    networks:
      - tmsnetwork
    
  auth:
    image: tms-authapi
    container_name: tms.authapi
    build:
      context: .
      dockerfile: Auth.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Container
      - ASPNETCORE_URLS=http://+:5001
    ports:
      - "5001:5001"
    links:
      - db:db
      - consul:consul
    depends_on:
      - db
      - consul
    networks:
      - tmsnetwork

  trip:
    image: tms-tripapi
    container_name: tms.tripapi
    build:
      context: .
      dockerfile: Trip.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Container
      - ASPNETCORE_URLS=http://+:5002
    ports:
      - "5002:5002"
    links:
      - db:db
      - consul:consul
    depends_on:
      - db
      - consul
    networks:
      - tmsnetwork
      
  ui:
    image: tms-ui
    container_name: tms.ui
    build:
      context: .
      dockerfile: UI/Dockerfile
    ports:
      - "8080:80"
    links:
      - gateway:gateway
    networks:
      - tmsnetwork

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - tmsnetwork  

  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul
    ports:
      - "8500:8500"
    networks:
      - tmsnetwork
