version: '3.4'

networks:
  tmsnetwork:
    driver: bridge

services:
  gateway:
    image: tms-gatewayapi
    container_name: tms.gatewayapi
    build:
      context: .
      dockerfile: Gateway.Api/Dockerfile
    links:
      - auth:auth
      - trip:trip
    networks:
      - tmsnetwork
    
  auth:
    image: tms-authapi
    container_name: tms.authapi
    build:
      context: .
      dockerfile: Auth.Api/Dockerfile
    links:
      - db:db
      - consul:consul
    depends_on:
      - db
      - consul
    networks:
      - tmsnetwork

  trip:
    image: tms-tripapi
    container_name: tms.tripapi
    build:
      context: .
      dockerfile: Trip.Api/Dockerfile
    links:
      - db:db
      - consul:consul
    depends_on:
      - db
      - consul
    networks:
      - tmsnetwork
      
  ui:
    image: tms-ui
    container_name: tms.ui
    build:
      context: .
      dockerfile: UI/Dockerfile
    links:
      - gateway:gateway
    networks:
      - tmsnetwork

  db:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    networks:
      - tmsnetwork

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - db
    networks:
      - tmsnetwork

  consul:
    image: consul:latest
    command: consul agent -dev -log-level=warn -ui -client=0.0.0.0
    hostname: consul
    container_name: consul
    networks:
      - tmsnetwork
